### ISSUE TITLE
Remove dependency on contextlib2

### ISSUE THREAD

**Issue by mcepl** [python-trio/sphinxcontrib-trio#18]
[avoid_contextlib2.patch](https://github.com/python-trio/sphinxcontrib-trio/files/2539184/avoid_contextlib2.patch.txt)

**Comment by njsmith** [comment]
There is no dependency on contextlib2... if you have contextlib2 installed then we apply the same autodetection logic that we use for regular contextlib, but if you don't have contextlib2 installed then that's fine. AFAICT the patch here just breaks those projects, and this is a strange issue with no text attached, so... I guess closing this? Feel free to re-open if there's something I'm missing. But if you do then please add some words to explain :-)

**Comment by mcepl** [comment]
Thank you.
