### ISSUE TITLE
Fix compatibility with sphinx 2.1

### ISSUE THREAD

**Issue by njsmith** [python-trio/sphinxcontrib-trio#23]
The next version of sphinx is adding `:async:`, `:staticmethod:`, `:classmethod:` attributes for functions and methods, along with autodoc support: https://github.com/sphinx-doc/sphinx/pull/6295

This is great, but will almost certainly conflict with this plugin :-).

A few differences I noticed:

* When a method is marked `:async:`, they add the word "async" to the signature. We add "await". I think "await" is better, because (a) people read docs to learn how to use things, (b) showing how to use it is more consistent with how we show generators, context managers, decorators, etc.. E.g. if you have an async function that returns an async generator, we show the signature like `async for ... in await somefunc(...)`, while if we follow sphinx then it would be `async for ... in async somefunc(...)`, which is just confusing. OTOH whatever sphinx does by default might become the standard, and if people are used to seeing it one way then it'll be confusing if we do it a different way.

* When a method is marked `:staticmethod:`, they add the word "static" to the signature, instead of "staticmethod". Kinda odd but whatever.

* I think their autodoc sniffing is currently broken when you combine multiple features together, e.g. it will give the wrong results if you have an async classmethod. sphinxcontrib-trio needed a [ton](https://github.com/python-trio/sphinxcontrib-trio/blob/643ca5d9724e04cd5eace6946e76f8b7eb28e2b1/sphinxcontrib_trio/__init__.py#L238-L286) of [hacks](https://github.com/python-trio/sphinxcontrib-trio/blob/643ca5d9724e04cd5eace6946e76f8b7eb28e2b1/sphinxcontrib_trio/__init__.py#L288-L300) to [get the details right](https://github.com/python-trio/sphinxcontrib-trio/blob/643ca5d9724e04cd5eace6946e76f8b7eb28e2b1/sphinxcontrib_trio/__init__.py#L350-L363). And our test suite for these features is wayyy more thorough than sphinx's. They seem to be reinventing all this from scratch, so they're having to rediscover all this...

CC: @tk0miya

**Comment by tk0miya** [comment]
Good point.

At first point, personally, I prefer to describe the behavior of the functions and methods rather than to describe how to use.

Next, about "static" prefix, I agree with you. I prefer "staticmethod" too. The prefix comes from older Sphinx's `.. staticmethod` directive. Nothing changed.
But +1 for changing it.

Last, thank you for advice. I'm beginner of python domain and autodoc module. This is my first journey to the domain. So it would be very helpful if you share your knowledge to us.

**Comment by njsmith** [comment]
> At first point, personally, I prefer to describe the behavior of the functions and methods rather than to describe how to use.

Do you have another suggestion for how to document decorators, context managers, and generators?

> Next, about "static" prefix, I agree with you. I prefer "staticmethod" too. The prefix comes from older Sphinx's .. staticmethod directive. Nothing changed.

Hah, whoops, I didn't even realize we changed this! I guess staticmethods are extremely rare (classmethods are almost always used instead), so we didn't notice...

**Comment by tk0miya** [comment]
>Do you have another suggestion for how to document decorators, context managers, and generators?

At least, `py:decorator` directive describe itself as `@decorator`. But, I can't say it is best way. TBH, I don't have an answer for the representation.

At present, we have two kinds of representation. The first one describes the objects as how used like trio extension does. Decorator is one of them. And another describes objects as classification (I don't know the best wording for this. We can say them as type, behavior and so on.). Staticmethod is one of them. We've never call it like `static foo()` in python. The "static" prefix only describes the classification of the methods, not usage.

I think both are enough better. But we should choose either way. I think mixed representation will cause readers confused.

>Hah, whoops, I didn't even realize we changed this! I guess staticmethods are extremely rare (classmethods are almost always used instead), so we didn't notice...

It seems the prefix had been used since its beginning (I also did not know...)
https://github.com/sphinx-doc/sphinx/commit/8b0f48a38b#diff-3e96261dd7ff47fee44cbd61b80a3cbfR217

**Comment by tk0miya** [comment]
In according to my idea (preference?), I posted `:property:` option to `py:method` directive. It describes the object as "property prop_name".
https://github.com/sphinx-doc/sphinx/pull/6320/files#diff-6af9db0432907bf2ccaadf2d88b0c141R609

What do you think about this case?

**Comment by njsmith** [comment]
Sphinx 2.1 is out now, and indeed broke us, e.g. trustme CI is broken right now: https://travis-ci.org/python-trio/trustme/jobs/540541000

```
/home/travis/build/python-trio/trustme/trustme/__init__.py:docstring of trustme.CA.cert_pem:1:Error in "py:method" directive:
unknown option: "property".
.. py:method:: CA.cert_pem
   :module: trustme
   :property:
```

It looks like the immediate cause is that sphinx 2.1 added the `PropertyDocumenter` in autodoc, which overrides the old `AttributeDocumenter`, and treats properties as `.. py:method::` with a `:property` flag. sphinxcontrib-trio's `AttributeDocumenter` is getting overridden by sphinx's `PropertyDocumenter`, so we end up with input that contains `:property:`, but then sphinxcontrib-trio's `.. py:method` override is still in effect and doesn't know how to cope.

I guess this is what @tk0miya was asking about in the comment right above this one that I never found the time to reply to. whoops.

I find the idea of documenting properties kind of weird, because this is an implementation detail. From the user's point of view, there's no difference in how you use a regular attribute versus a property attribute; they're just attributes. So putting this in the docs I think is not very useful, and kinda distracting.

This is why sphinxcontrib-trio doesn't have any special support for properties – IMO they should be handled by `AttributeDocumenter`, and currently sphinxcontrib-trio doesn't bother overriding `AttributeDocumenter`. I did think about it, in order to handle `@abstractmethod` + `@property`, but I'm not really sure what the best thing to do there is plus it was a lot of work just for that case. So far we haven't done anything.

Anyway..... given that we need to unbreak our builds ASAP, and that the `:property:` feature seems unnecessary, maybe the short-term fix is to have sphinxcontrib-trio disable `PropertyDocumenter` entirely?

-----

I'm still not sure what to do about this part:

> At present, we have two kinds of representation. The first one describes the objects as how used like trio extension does. Decorator is one of them. And another describes objects as classification (I don't know the best wording for this. We can say them as type, behavior and so on.). Staticmethod is one of them. We've never call it like static foo() in python. The "static" prefix only describes the classification of the methods, not usage.

> I think both are enough better. But we should choose either way. I think mixed representation will cause readers confused.

The problem is that for some things there is no way to describe them "as used": staticmethod, abstractmethod, type hints. So we have to invent something to put in the signature. (Usually somewhat inspired by the notation Python uses to define these objects.) But, for other things, the only reasonable way to describe them is "as used": decorators, context managers, iterators, etc. Like, here's some real examples from Trio's docs:

```python
async with trio.open_nursery() as nursery
with trio.open_move_on_after(seconds) as cancel_scope
```

(Actual doc links: [open_nursery](https://trio.readthedocs.io/en/latest/reference-core.html#trio.open_nursery), [move_on_after](https://trio.readthedocs.io/en/latest/reference-core.html#trio.move_on_after).)

It would definitely not be clearer if we wrote these as:

```python
async-context-manager trio.open_nursery()
context-manager trio.move_on_after(seconds)
```

This version also has strictly less information – you lose the hint about what kind of object comes out of the context manager.

...as writing this, I just noticed another way that sphinx prefers "as used" over "as defined" – when it writes the function as `trio.open_nursery`, with the `trio.` namespace in front, that's showing how you use it, not how it's defined.

So, anyway, the point is – we can't pick just one way and use it consistently. It's not possible.

And I think that's OK. Nobody expects the docs to be a copy/paste of how the function was defined, and they don't expect them to be something they can copy/paste into their code either. They just want something they can read and understand.

So... according to this principle, both `async` and `await` are reasonable options, and we still have to pick :-).

I think the main arguments for `await` are:

* Users come to the docs to learn how to use something, so all else being equal, showing them how to use it is more useful than showing how it's defined.
* It makes it much clearer when you want to distinguish `async with foo()` versus `await foo()` versus `async with await foo()`

**Comment by njsmith** [comment]
Fixed in #25.

I ended up adding `:property:` support to our `py:method` directive. This way it's OK if sphinx uses `PropertyDocumenter`, and it's also ok if users start using `:property:` directly. It doesn't write `property` into the output, though, it just drops the parens. But it's still indexed as a method, which is weird. I think documenting properties as attributes makes more sense in general.

**Comment by tk0miya** [comment]
>From the user's point of view, there's no difference in how you use a regular attribute versus a property attribute; they're just attributes. 

No, they are different. Users can assign new values to attributes. But they can't do to properties.
```
>>> class Foo:
...     @property
...     def bar(self):
...         return 1
...
>>> Foo().bar
1
>>> Foo().bar = 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```

I know library authors can make them assign-able. But I suppose almost properties are not assign-able. So I think document should not describe them as attributes.

>So, anyway, the point is – we can't pick just one way and use it consistently. It's not possible.
...
>I think the main arguments for await are:

There are some another usages for coroutines. For example, we can wrap them with Task via `asyncio.create_task()` ([ref](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task)). I'm not familiar with asyncio. But it seems `await` is not a only way to use them.

The generators are similar case. We usually use them via "with g:" syntax. But some kinds of generator takes arguments on continuation via `g.send()`.

I don't know these cases are special (or rare). But I think it is hard to know the intention of library authors from source code. So I choose to describe the classification of them instead of usage.

Note: I don't think trio's choice is worse. It is also reasonable.


In addition, I'm thinking about representation of decorator now. As you know, there are no special syntax for it. It looks like a simple function in its declaration. So it is difficult to represent it "as defined".

BTW, it is also hard to represent them "as used". Some kind of decorators takes arguments before decoration:
```
@pytest.mark.skipif(condition, reason='blah blah blah')
def test_foo():
    pass
```
To represent this correctly, we need to know the decorator takes arguments or not...

**Comment by njsmith** [comment]
> I know library authors can make them assign-able. But I suppose almost properties are not assign-able. 

I've read and written a *lot* of python docs, so I guess I'm part of your target audience here. It would never, ever occur to me that "property" was supposed to mean "readonly". The idea that most people don't make properties settable doesn't match my experience at all; in fact I would have said that overriding property setting was one of the main use cases for properties.

I'm not claiming my experience is universal. But I'm confident that for a substantial subset of your audience, this just doesn't work.

Now, I do like the idea of allowing `:readonly:` and `:readwrite:` annotations on attributes in general. And for properties, autodoc could add these annotations directly.

> There are some another usages for coroutines. For example, we can wrap them with Task via asyncio.create_task() (ref). I'm not familiar with asyncio. But it seems await is not a only way to use them.

I'm extremely familiar with asyncio :-). You're right: anything you can call like `await blah()`, you can also call like `create_task(blah())`. But I don't think this is a problem at all. When you see `await blah()` in the docs, it doesn't mean you have to literally copy-paste that text into your program. Its purpose is to communicate something. And anyone who uses asyncio understands that you can switch between these two types of code. They're already used to seeing both forms in their code every day. It's just not a source of confusion.

> The generators are similar case. We usually use them via [`for ... in g`] syntax. But some kinds of generator takes arguments on continuation via g.send().

Generators that accept `send` really are extremely rare – I'd guess well less than 1% of generators. So even if you do tell people it's a generator, they won't think that that means it accepts `send`, because... it doesn't mean that. That has to be communicated some other way, like in the text of the function documentation.

It is true that for the rare generator that shouldn't be used in a `for` loop, then it's better not to document it using `for ... in gen(...)`. But that's fine, just don't put the `:for:` attribute on it. Maybe it would be nice to have a way to disable sniffing for autodoc here. That seems like a reasonable feature: `:no-sniff-attributes:` maybe?

> Some kind of decorators takes arguments before decoration:

Yeah, but I think we can handle this fine right now?

```
.. function:: skipif(condition, reason)
   :decorator:
```

There's no way to generate this automatically in autodoc, because python just doesn't give any way to figure this out from the source code. But that's a python limitation. Nothing we can do about that.

**Comment by Puncher1** [comment]
How would I make that `await` is in title instead of `async`? Couldn't find any related post or something except of this issue.
